### ISSUE TITLE
HW4 ready for grading

### ISSUE THREAD

**Issue by SunnyStare** [SunnyStare/SU-MT4007-Statistisk-databehandling#4]
OBS! Thera are three files corresponding to two parts: Joining data.ipynb,  SQL.ipynb and Regex.ipynb.

**Comment by oscarsjostrand** [comment]
Joining Data:
* We ignore the first part corresponding to HW3
* The table consisting of the ratio should be from 2015-2019 and ordered in descending order.  From this table we will analyse the five countries growth rate over the last 10 years. 
* However, interesting solution in finding the slope of the linear regression. 

SQL: 
Looks good, good work!

Regex:
Looks good, good work!

**Comment by LeoLevenius** [comment]
# $${\color{green}\text{Godkänt.}}$$
